"""Every Civilization VI accessor named in ``lua/**/*.lua`` must be on the checked-in allowlist.

The gap this closes. On 2026-09-21 the same defect was found three separate times in one day: a
body calling a method Civilization VI does not have, behind an ``if obj.Method then`` guard or a
``pcall`` that swallowed the absence, so the harness reported an honest-looking empty value for
hundreds of steps and the dependent action could never become available.
``cities.set_production`` was dead for 399 steps on ``buildQueue:GetAvailableProduction()``
(fixed in 1d0b372); ``units.promote`` was dead everywhere on ``unit:GetAvailablePromotions()``
(fixed in 6606d4b); ``lua/ingame/city_orders.lua`` used
``CityOperationTypes.PARAM_PRODUCTION_ITEM``, a key that does not exist. The full audit
(``specs/002-civ-playing-harness/spikes/lua-accessor-audit-2026-09-21.md``) found 28 such names
across 38 call sites.

Why no other test catches it. The T213 spike proved every observation body "produces a value"
against a live client. An empty list *is* a value, so that proof passed on every one of these.
"Does the body answer?" cannot distinguish a real empty list from a phantom accessor; only "does
this name exist in the game?" can.

Why an allowlist and not a live check. The only authority on whether a name exists is the
installed game, and CI has no Civilization VI. ``lua/ACCESSORS.txt`` is that authority's answer,
written down: one line per accessor the harness uses, each carrying a ``steamassets/``-relative
``file:line`` where Firaxis' own shipped Lua uses that exact name. It was generated by searching
the 645 shipped ``.lua`` files and cross-checking against the engine binaries' own Lua binding
tables; see the audit spike for the method. The allowlist is small (216 names) and cited, with no
wildcard, precisely so that adding an entry is a deliberate act with evidence attached.

The assertion runs in both directions on purpose. A name in the Lua that is not listed is the
phantom guard. A name listed that the Lua no longer uses is the rot guard: without it the file
would silently accumulate permissions for calls nobody makes, and the next phantom could hide
behind a stale neighbour.

This test reads text and needs no Lua runtime, so it runs under the plain suite as well as under
``uv run --with lupa``.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
LUA_ROOT = REPO_ROOT / "lua"
ALLOWLIST = LUA_ROOT / "ACCESSORS.txt"

#: ``obj:Method(`` -- a call on whatever object the expression to the left produced. The colon
#: form is the only one Lua uses for method calls, which is what makes this extraction exact
#: rather than heuristic.
_METHOD_RE = re.compile(r":\s*([A-Za-z_][A-Za-z0-9_]*)\s*\(")

#: ``Namespace.Name`` where the namespace starts with a capital -- ``UnitManager.RequestOperation``,
#: ``PlayerOperations.PARAM_X``, ``ActivityTypes.ACTIVITY_AWAKE``. Deliberately not restricted to
#: calls: three of the audit's findings were *constants* that read back nil
#: (``UnitActivityType.ACTIVITY_OPERATION``, ``UnitOperationTypes.SPY_MISSION``,
#: ``CityOperationTypes.PARAM_PRODUCTION_ITEM``), which is the same defect wearing different
#: clothes -- a nil key silently poisons the table it is written into.
_DOTTED_RE = re.compile(r"\b([A-Z][A-Za-z0-9_]*)\s*\.\s*([A-Za-z_][A-Za-z0-9_]*)\b")

#: ``local x``/``local function x`` -- a name declared in our own file is ours, not the game's, so
#: ``entry.foo`` on a local table is not an accessor claim about Civilization VI. Matching by name
#: (rather than by scope) is deliberately over-broad in the safe direction: it can only ever
#: *exclude* a name we defined ourselves somewhere in the same file.
_LOCAL_RE = re.compile(r"\blocal\s+(?:function\s+)?([A-Za-z_][A-Za-z0-9_]*)")


def _lua_files() -> list[Path]:
    return sorted(LUA_ROOT.rglob("*.lua"))


def extract_accessors() -> dict[str, list[str]]:
    """Every accessor name the harness's Lua uses, mapped to its ``file:line`` call sites.

    Comment-only lines are skipped: a name discussed in a citation comment (and every body now
    carries several) is documentation, not a call.
    """
    found: dict[str, list[str]] = {}
    for path in _lua_files():
        relative = path.relative_to(REPO_ROOT)
        declared_locally: set[str] = set()
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            declared_locally.update(_LOCAL_RE.findall(line))
            if line.lstrip().startswith("--"):
                continue
            for name in _METHOD_RE.findall(line):
                found.setdefault(f":{name}", []).append(f"{relative}:{number}")
            for namespace, attribute in _DOTTED_RE.findall(line):
                if namespace in declared_locally:
                    continue
                found.setdefault(f"{namespace}.{attribute}", []).append(f"{relative}:{number}")
    return found


def load_allowlist() -> dict[str, str]:
    """``{accessor name: steamassets-relative file:line}`` from ``lua/ACCESSORS.txt``."""
    entries: dict[str, str] = {}
    for number, raw in enumerate(ALLOWLIST.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        assert len(parts) == 2, (
            f"{ALLOWLIST.name}:{number} is not `<accessor>  <file:line>`: {raw!r}. "
            "Every entry carries exactly one citation."
        )
        name, citation = parts
        assert name not in entries, f"{ALLOWLIST.name}:{number} lists {name!r} twice"
        entries[name] = citation
    return entries


def test_every_accessor_in_the_lua_is_on_the_allowlist() -> None:
    """The phantom guard.

    A name here that the allowlist does not carry has no evidence that Civilization VI has it.
    That is exactly the state ``GetAvailableProduction`` and ``GetAvailablePromotions`` were in
    while they silently returned ``[]``.
    """
    used = extract_accessors()
    allowed = load_allowlist()
    unlisted = {name: sites for name, sites in used.items() if name not in allowed}
    assert not unlisted, (
        "lua/**/*.lua names accessors that are not in lua/ACCESSORS.txt:\n"
        + "\n".join(
            f"  {name}  <- {', '.join(sites[:6])}" for name, sites in sorted(unlisted.items())
        )
        + "\n\nIf the accessor is real, add it to lua/ACCESSORS.txt with a steamassets/ file:line "
        "showing Firaxis' own code using that exact name. If you cannot find one, the game does "
        "not have it -- see specs/002-civ-playing-harness/spikes/lua-accessor-audit-2026-09-21.md."
    )


def test_every_allowlist_entry_is_still_used() -> None:
    """The rot guard.

    An allowlist that outlives its callers stops being a list of what we verified and becomes a
    blanket permission slip -- and a stale neighbour is exactly where the next phantom would hide.
    """
    used = extract_accessors()
    stale = sorted(name for name in load_allowlist() if name not in used)
    assert not stale, (
        "lua/ACCESSORS.txt lists accessors that lua/**/*.lua no longer uses:\n"
        + "\n".join(f"  {name}" for name in stale)
        + "\n\nRemove them. The allowlist is a record of names we checked against the shipped "
        "game for calls we actually make, not a standing permission."
    )


def test_allowlist_citations_look_like_shipped_ui_paths() -> None:
    """Each citation points into the shipped game, with a line number.

    Not a proof -- CI has no Civilization VI to check against -- but it keeps the column from
    degrading into free text, which is how a cited allowlist quietly becomes an uncited one.
    """
    bad = {
        name: citation
        for name, citation in load_allowlist().items()
        if not re.fullmatch(r"(?:base|dlc|ctp|debug|launchpad)/[\w./-]+\.lua:\d+", citation)
    }
    assert not bad, (
        "lua/ACCESSORS.txt citations must be `<steamassets-relative path>.lua:<line>`:\n"
        + "\n".join(f"  {name}  {citation}" for name, citation in sorted(bad.items()))
    )


def test_the_three_known_phantoms_would_be_rejected() -> None:
    """The check that the check works.

    These three names are the ones that actually shipped and actually cost play time. None is in
    the allowlist, so reintroducing any of them fails
    :func:`test_every_accessor_in_the_lua_is_on_the_allowlist` rather than returning ``[]`` for
    another 399 steps.
    """
    allowed = load_allowlist()
    for phantom in (
        ":GetAvailableProduction",  # lua/gamecore/cities.lua, fixed in 1d0b372
        ":GetAvailablePromotions",  # lua/gamecore/units.lua, fixed in 6606d4b
        "CityOperationTypes.PARAM_PRODUCTION_ITEM",  # lua/ingame/city_orders.lua
    ):
        assert phantom not in allowed, (
            f"{phantom} is a name Civilization VI does not have (accessor audit, 2026-09-21); "
            "it must never be allowlisted."
        )


def test_the_audit_found_lua_to_check() -> None:
    """A vacuous pass is not a pass: the extractor must actually see the bodies."""
    files = _lua_files()
    assert len(files) >= 25, f"expected the harness's Lua bodies, found {len(files)}"
    used = extract_accessors()
    assert len(used) >= 150, f"expected the full accessor surface, extracted {len(used)} names"
    assert ":GetMovesRemaining" in used, "the extractor is not seeing ordinary method calls"
    assert "UnitManager.RequestOperation" in used, "the extractor is not seeing namespaced calls"
    assert "PlayerOperations.PARAM_X" in used or "UnitOperationTypes.PARAM_X" in used, (
        "the extractor is not seeing enum constants, which is where three phantoms hid"
    )
